export const lightTheme = {
  background:       "#ffffff",
  surface:          "#f9f9f9",
  surfaceBorder:    "#dddddd",
  text:             "#212529",
  textSecondary:    "#555555",
  inputBackground:  "#ffffff",
  inputBorder:      "#cccccc",
  tableHeader:      "#f0f0f0",
  tableRowHover:    "#f5f5f5",
  tableRowAlt:      "#fafafa",
  badgeBackground:  "#e8f0fe",
  badgeText:        "#1a73e8",
  btnPrimary:       "#0d6efd",
  btnPrimaryText:   "#ffffff",
  btnDanger:        "#dc3545",
  btnDangerText:    "#ffffff",
  btnSecondary:     "#6c757d",
  btnSecondaryText: "#ffffff",
  btnToggle:        "#f0f0f0",
  btnToggleText:    "#212529",
  linkColor:        "#0d6efd",
  errorColor:       "#dc3545",
};

export const darkTheme = {
  background:       "#121212",
  surface:          "#1e1e1e",
  surfaceBorder:    "#333333",
  text:             "#e0e0e0",
  textSecondary:    "#aaaaaa",
  inputBackground:  "#2a2a2a",
  inputBorder:      "#444444",
  tableHeader:      "#2a2a2a",
  tableRowHover:    "#2a2a2a",
  tableRowAlt:      "#1a1a1a",
  badgeBackground:  "#1a3a6b",
  badgeText:        "#90b8f8",
  btnPrimary:       "#1a6efd",
  btnPrimaryText:   "#ffffff",
  btnDanger:        "#c82333",
  btnDangerText:    "#ffffff",
  btnSecondary:     "#5a6268",
  btnSecondaryText: "#ffffff",
  btnToggle:        "#2a2a2a",
  btnToggleText:    "#e0e0e0",
  linkColor:        "#90b8f8",
  errorColor:       "#f87171",
};